kind: Template
apiVersion: v1

parameters:
- name: DJANGO_SECRET_KEY
  from: '[a-zA-Z0-9]{50}'
  generate: expression
  required: true

objects:
- kind: Secret
  apiVersion: v1
  metadata:
    name: application
    labels:
      app: {{ cookiecutter.project_slug }}
      component: application
  stringData:
    secret-key: ${DJANGO_SECRET_KEY}
