apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../template
nameSuffix: -hello
patchesJson6902:
- target:
    group: batch
    version: v1beta1
    kind: CronJob
    name: application-job
  path: patch.yaml
