# Painless development and deployment with Docker. Base configuration.
# Visit the docs at https://docs.docker.com/compose/

version: '3'

volumes:
  database_data: {}

services:
  application:
    ports:
      - '80:80'
{%- if cookiecutter.database in ['Postgres', 'MySQL'] %}
    depends_on:
      - database
{% endif %}

{%- if cookiecutter.database == 'Postgres' %}
  database:
    image: postgres
    volumes:
      - database_data:/var/lib/postgresql/data
{%- elif cookiecutter.database == 'MySQL' %}
  database:
    image: MySQL
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - database_data:/var/lib/mysql/data
{%- endif %}
