apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
{%- if cookiecutter.environment_strategy == 'shared' %}
namespace: {{ cookiecutter.cloud_project }}
{%- endif %}
commonLabels:
{%- if cookiecutter.environment_strategy == 'dedicated' %}
  app: {{ cookiecutter.project_slug }}
{%- endif %}
  component: application
configMapGenerator:
- name: application
  envs:
  - application.env
{%- if cookiecutter.cronjobs == 'complex' %}
bases:
- cronjob
{%- endif %}
crds:
- route-crd.yaml
resources:
{%- if cookiecutter.cronjobs == 'simple' %}
- cronjob.yaml
{%- endif %}
- deployment.yaml
- rolebinding.yaml
- route.yaml
- secret.yaml
- service.yaml
